# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: testjoin
            asset_name: testjoin-linux
          - os: windows-latest
            artifact_name: testjoin.exe
            asset_name: testjoin.exe
          - os: macos-latest
            artifact_name: testjoin
            asset_name: testjoin-mac

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'
      - run: nim c -d:ssl -d:release --opt:size --passL:-s testjoin.nim
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
